# Generated by Django 3.1.5 on 2021-01-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='status_text',
            new_name='task_text',
        ),
    ]
